### ISSUE TITLE
Reason for the fork?

### ISSUE THREAD

**Issue by bachp** [jabesq/netatmo-api-python#9]
What is the reason for this fork used in home-assistant? The pypi package is from the original author.

**Comment by danielperna84** [comment]
Presumably because the original module didn't meet the requirements back then for the implementation the author of this fork had planned.
Unfortunately the modules are now incompatible. I started implementing the webhooks for the cameras a while ago based on the original module (I wasn't awar a fork is being used). This didn't work out though since the originaly module can't be referenced anymore because it conflicts with the fork. And because I would have needed to start from scratch again to be compatible with the fork I just stopped looking further into it and build a simple webapp that receives the webhooks and manually fires events. :-/
